project:
  type: book

book:
  title: "Exploration of Health indicator and Modeling"
  subtitle: "A Journey of Inference and Predictions"
  author: "Huber Daniel, Sever Alin & Girardin Robin"
  date: "11/28/2025"
  chapters:
    - index.qmd
    - part: "Part I: Obesity" 
      chapters: 
        - linear_model.qmd
        - support_vector_machine.qmd
    - part: "Part II: Mental Health"
      chapters:
        - glm-binomial.qmd
        - gam-binomial.qmd
    - part: "Part III: Alcohol Consumption"
      chapters:
        - glm_poisson.qmd
        - neural_network.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    code-summary: "Show/Hide code"
    toc: true
    toc-depth: 3
    number-sections: true



